import { ArtStylePreset } from "@/types/style";
import { ModelProviderConfig } from "@/types/model";
import { PageLayoutTemplate } from "@/types/comic";

export const DEFAULT_STYLES: ArtStylePreset[] = [
  {
    id: "style_cyberpunk_action",
    name: "Neon Cyberpunk Comic",
    category: "anime",
    description: "High-octane superhero action with electric neon energy, motorcycle chase through rainy city streets, and bold comic inking.",
    previewUrl: "/styles/cyberpunk-action-chase.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["9:16", "16:9", "4:3"],
    mixing: {
      styleStrength: 98,
      characterStyle: "neon-cyberpunk-hero",
      environmentStyle: "rainy-neon-city",
      lineArtStrength: 94,
      shadingStrength: 90,
      colorLevel: 95,
      realismLevel: 55,
      textureLevel: 75,
      detailLevel: 95,
    },
    promptKeywords: [
      "high-octane cyberpunk comic book art",
      "dynamic vertical panel split composition",
      "motorcycle chase in rainy neon city",
      "electric blue and red hair energy glow",
      "futuristic red visor goggles",
      "reflective wet asphalt pavement",
      "dramatic action camera perspective",
    ],
    negativeKeywords: ["blurry", "low contrast", "dull lighting", "flat cartoon", "washed out"],
  },
  {
    id: "style_hearth_fantasy",
    name: "Whimsical Hearth Fantasy",
    category: "illustration-fine-art",
    description: "Cozy fairytale storybook illustration with warm wood-fired oven lighting, rustic cottage kitchen details, and magical baking.",
    previewUrl: "/styles/whimsical-cottage-fantasy.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["4:3", "1:1", "16:9"],
    mixing: {
      styleStrength: 95,
      characterStyle: "storybook-fantasy-folk",
      environmentStyle: "warm-rustic-cottage",
      lineArtStrength: 78,
      shadingStrength: 80,
      colorLevel: 85,
      realismLevel: 50,
      textureLevel: 85,
      detailLevel: 90,
    },
    promptKeywords: [
      "whimsical fantasy storybook comic",
      "cozy rustic timber cottage kitchen",
      "warm glowing oven firelight",
      "magical baking with glowing golden steam",
      "charming halfling baker character",
      "detailed wood grain and copper cookware",
    ],
    negativeKeywords: ["harsh neon", "cold tones", "dark dystopian", "sharp modern angles"],
  },
  {
    id: "style_royal_otome",
    name: "Royal Otome Romance",
    category: "anime",
    description: "Luxurious noble romance webtoon aesthetic with sunlit marble balconies, blooming rose gardens, and delicate anime lighting.",
    previewUrl: "/styles/royal-otome-romance.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["16:9", "9:16", "4:3"],
    mixing: {
      styleStrength: 94,
      characterStyle: "otome-romance-princess",
      environmentStyle: "ornate-marble-palace-garden",
      lineArtStrength: 70,
      shadingStrength: 75,
      colorLevel: 90,
      realismLevel: 52,
      textureLevel: 50,
      detailLevel: 92,
    },
    promptKeywords: [
      "romantic otome manhwa webtoon style",
      "sun-drenched palace terrace with blooming roses",
      "golden sunlight rays and floating dust motes",
      "luxurious white and sapphire ballgown",
      "elegant blonde noblewoman reading spellbook",
      "soft dreamy pastel aesthetic",
    ],
    negativeKeywords: ["harsh dark shadows", "gore", "heavy black crosshatch", "rough sketchy lines"],
  },
  {
    id: "style_modern_graphic_novel",
    name: "Modern Graphic Novel",
    category: "western-comic",
    description: "Refined ligne claire European graphic novel style with crisp contour inking and dramatic ensemble character storytelling.",
    previewUrl: "/styles/dramatic-ensemble-graphic-novel.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["1:1", "4:3", "16:9"],
    mixing: {
      styleStrength: 92,
      characterStyle: "clean-line-dramatic-ensemble",
      environmentStyle: "contemporary-urban-interior",
      lineArtStrength: 95,
      shadingStrength: 75,
      colorLevel: 75,
      realismLevel: 65,
      textureLevel: 50,
      detailLevel: 88,
    },
    promptKeywords: [
      "modern indie graphic novel art",
      "crisp clear ligne claire line art",
      "cinematic ensemble character lineup",
      "stylish apartment with night city window",
      "balanced flat color palette with subtle shadows",
      "narrative comic panel composition",
    ],
    negativeKeywords: ["chibi", "sketchy rough ink", "distorted anatomy", "exaggerated manga eyes"],
  },
  {
    id: "style_retro_pulp_noir",
    name: "Retro Pulp & Noir",
    category: "western-comic",
    description: "Atmospheric 1970s pulp action comic with muscular stylized anatomy, smoky jazz lounge lighting, and rich amber shadows.",
    previewUrl: "/styles/retro-pulp-jazz-noir.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["16:9", "21:9", "4:3"],
    mixing: {
      styleStrength: 96,
      characterStyle: "muscular-pulp-action",
      environmentStyle: "smoky-mahogany-jazz-bar",
      lineArtStrength: 94,
      shadingStrength: 92,
      colorLevel: 80,
      realismLevel: 62,
      textureLevel: 70,
      detailLevel: 90,
    },
    promptKeywords: [
      "vintage 1970s pulp comic book art",
      "bold expressive brush and ink linework",
      "muscular jazz pianist smoking cigar at grand piano",
      "warm mahogany bar with amber pendant lighting",
      "dramatic cinematic framing",
      "classic action hero aesthetic",
    ],
    negativeKeywords: ["clean digital vector", "pastel cute", "flat manga", "blurry rendering"],
  },
  {
    id: "style_manga_screentone",
    name: "Classic Screentone Manga",
    category: "manga",
    description: "Crisp black and white ink line art with traditional manga screentone shading, dynamic hatching, and high contrast.",
    previewUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
    screentoneSupported: true,
    idealAspectRatios: ["4:3", "1:1", "16:9"],
    mixing: {
      styleStrength: 95,
      characterStyle: "manga-screentone",
      environmentStyle: "detailed-hatch",
      lineArtStrength: 90,
      shadingStrength: 85,
      colorLevel: 0, // pure B&W
      realismLevel: 40,
      textureLevel: 80,
      detailLevel: 85,
    },
    promptKeywords: [
      "authentic Japanese manga style",
      "sharp black ink linework",
      "dot screentone shading",
      "dramatic cross-hatching",
      "monochrome",
      "high ink contrast",
      "retro Weekly Shonen jump aesthetic",
    ],
    negativeKeywords: ["color", "photorealistic", "soft gradients", "western 3d render", "smooth plastic"],
  },
  {
    id: "style_cinematic_anime",
    name: "Cinematic Modern Anime",
    category: "anime",
    description: "Lush theatrical animation aesthetic with dramatic atmospheric lighting, rich film grain, and expressive linework.",
    previewUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
    screentoneSupported: false,
    idealAspectRatios: ["16:9", "21:9", "4:3"],
    mixing: {
      styleStrength: 90,
      characterStyle: "modern-theatrical-anime",
      environmentStyle: "painted-cinematic-background",
      lineArtStrength: 75,
      shadingStrength: 80,
      colorLevel: 85,
      realismLevel: 55,
      textureLevel: 45,
      detailLevel: 90,
    },
    promptKeywords: [
      "theatrical anime still",
      "Makoto Shinkai inspired atmospheric lighting",
      "subtle chromatic aberration",
      "clean cel-shaded characters",
      "lush painted backgrounds",
      "cinematic depth of field",
    ],
    negativeKeywords: ["cheap 3d", "oversaturated neon", "monochrome", "western caricature", "deformed eyes"],
  },
  {
    id: "style_graphic_novel_noir",
    name: "Editorial Noir Graphic Novel",
    category: "western-comic",
    description: "Heavy ink chiaroscuro, brooding shadows, gritty urban textures, and restrained desaturated color palette.",
    previewUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    screentoneSupported: false,
    idealAspectRatios: ["16:9", "4:3", "1:1"],
    mixing: {
      styleStrength: 92,
      characterStyle: "heavy-ink-chiaroscuro",
      environmentStyle: "gritty-noir-urban",
      lineArtStrength: 95,
      shadingStrength: 95,
      colorLevel: 25,
      realismLevel: 65,
      textureLevel: 85,
      detailLevel: 88,
    },
    promptKeywords: [
      "hardboiled noir graphic novel",
      "deep ink pooling",
      "harsh directional shadows",
      "gritty film-noir chiaroscuro",
      "muted desaturated sepia and slate tones",
      "expressive brushed inking",
    ],
    negativeKeywords: ["bright anime", "chibi", "vibrant pastel", "flat vector", "plastic 3d"],
  },
  {
    id: "style_western_superhero",
    name: "Modern Western Comic",
    category: "western-comic",
    description: "Dynamic muscle anatomy, bold variable-weight ink lines, rich digital color highlights, and cinematic camera angles.",
    previewUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
    screentoneSupported: false,
    idealAspectRatios: ["4:3", "16:9", "1:1"],
    mixing: {
      styleStrength: 88,
      characterStyle: "western-comic-heroic",
      environmentStyle: "bold-rendered-city",
      lineArtStrength: 85,
      shadingStrength: 75,
      colorLevel: 80,
      realismLevel: 60,
      textureLevel: 50,
      detailLevel: 85,
    },
    promptKeywords: [
      "modern American comic book art",
      "bold brush and quill line work",
      "dynamic heroic composition",
      "digital coloring with rim light",
      "graphic novel panel",
    ],
    negativeKeywords: ["manga screentone", "photograph", "low resolution", "amateur sketch"],
  },
  {
    id: "style_seinen_cyberpunk",
    name: "Dark Seinen Cyberpunk",
    category: "manga",
    description: "Intricate mechanical greebles, rainy neon reflections over dark inking, mature anatomical proportions, and intense psychological atmosphere.",
    previewUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80",
    screentoneSupported: true,
    idealAspectRatios: ["16:9", "21:9", "4:3"],
    mixing: {
      styleStrength: 94,
      characterStyle: "mature-seinen",
      environmentStyle: "dense-cyberpunk-metropolis",
      lineArtStrength: 92,
      shadingStrength: 88,
      colorLevel: 35,
      realismLevel: 70,
      textureLevel: 75,
      detailLevel: 95,
    },
    promptKeywords: [
      "Otomo and Nihei inspired seinen manga",
      "dense architectural linework",
      "cybernetic cables and industrial textures",
      "high ink density",
      "atmospheric fog and rain reflections",
    ],
    negativeKeywords: ["childish cartoon", "kawaii", "flat colors", "blurry lines"],
  },
  {
    id: "style_watercolor_fantasy",
    name: "Atmospheric Watercolor Illustration",
    category: "illustration-fine-art",
    description: "Delicate pigment granulation, soft bleeding washes, organic pencil underdrawing, and lyrical fantasy warmth.",
    previewUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80",
    screentoneSupported: false,
    idealAspectRatios: ["4:3", "1:1", "16:9"],
    mixing: {
      styleStrength: 85,
      characterStyle: "storybook-watercolor",
      environmentStyle: "soft-pigment-wash",
      lineArtStrength: 60,
      shadingStrength: 70,
      colorLevel: 70,
      realismLevel: 45,
      textureLevel: 90,
      detailLevel: 75,
    },
    promptKeywords: [
      "delicate watercolor and gouache illustration",
      "paper grain texture",
      "visible brush washes and water blooms",
      "fine sepia ink contour",
      "whimsical storybook aesthetic",
    ],
    negativeKeywords: ["harsh digital vector", "3d render", "neon glow", "hard glossy edges"],
  },
  {
    id: "style_shonen_battle",
    name: "Shonen Battle Action Anime",
    category: "anime",
    description: "High-octane action anime with explosive elemental auras, crackling kinetic sparks, dynamic perspective angles, and intense battle speed lines.",
    previewUrl: "/characters/aoi-spark.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["16:9", "4:3", "1:1"],
    mixing: {
      styleStrength: 96,
      characterStyle: "explosive-shonen-action",
      environmentStyle: "dynamic-elemental-arena",
      lineArtStrength: 88,
      shadingStrength: 85,
      colorLevel: 95,
      realismLevel: 45,
      textureLevel: 65,
      detailLevel: 92,
    },
    promptKeywords: [
      "dynamic shonen battle anime keyframe",
      "intense glowing combat energy aura",
      "crackling electricity sparks",
      "extreme action perspective foreshortening",
      "high-speed motion blur lines",
      "Ufotable and Mappa inspired animation key visual",
      "crisp character cel shading with vivid rim lighting",
    ],
    negativeKeywords: ["static pose", "flat lighting", "dull colors", "washed out", "western cartoon"],
  },
  {
    id: "style_retro_90s_cel",
    name: "90s Golden Age Cel Anime",
    category: "anime",
    description: "Nostalgic 1990s television animation aesthetic with hand-painted plastic cel layers, authentic warm film grain, chromatic shadows, and retro cyberpunk flair.",
    previewUrl: "/characters/kaelen-warlord.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["4:3", "16:9", "1:1"],
    mixing: {
      styleStrength: 92,
      characterStyle: "vintage-cel-shading",
      environmentStyle: "painted-retro-background",
      lineArtStrength: 82,
      shadingStrength: 80,
      colorLevel: 75,
      realismLevel: 50,
      textureLevel: 70,
      detailLevel: 85,
    },
    promptKeywords: [
      "classic 1990s cel anime keyframe",
      "retro anime aesthetic",
      "hand-painted animation cel look",
      "subtle vintage CRT scanline texture",
      "Cowboy Bebop and Evangelion era color palette",
      "nostalgic film grain and chromatic aberration",
    ],
    negativeKeywords: ["modern glossy 3D", "flat vector", "oversaturated digital glow", "photorealistic"],
  },
  {
    id: "style_ghibli_nostalgia",
    name: "Whimsical Hand-Painted Anime",
    category: "illustration-fine-art",
    description: "Breathtaking hand-painted gouache backgrounds with billowing cumulonimbus clouds, lush verdant meadows, and heartwarming storybook charm.",
    previewUrl: "/characters/lord-thalassor.jpg",
    screentoneSupported: false,
    idealAspectRatios: ["16:9", "4:3", "21:9"],
    mixing: {
      styleStrength: 94,
      characterStyle: "whimsical-expressive-anime",
      environmentStyle: "lush-painted-nature",
      lineArtStrength: 65,
      shadingStrength: 75,
      colorLevel: 88,
      realismLevel: 48,
      textureLevel: 80,
      detailLevel: 88,
    },
    promptKeywords: [
      "Studio Ghibli inspired anime aesthetic",
      "Hayao Miyazaki painted sky with dramatic cumulus clouds",
      "lush gouache meadow scenery with wildflowers",
      "gentle warm sunlight diffusion",
      "heartfelt cinematic nostalgia",
      "clean expressive character contours",
    ],
    negativeKeywords: ["harsh neon", "heavy dark gore", "harsh CGI", "cold desaturated tones"],
  },
  {
    id: "style_dark_fantasy_manga",
    name: "Gothic Dark Fantasy Manga",
    category: "manga",
    description: "Grim, majestic medieval dark fantasy inking with relentless cross-hatching, weathered iron plate armor, ominous shadows, and gothic grandeur.",
    previewUrl: "/characters/ren-volt.jpg",
    screentoneSupported: true,
    idealAspectRatios: ["4:3", "16:9", "1:1"],
    mixing: {
      styleStrength: 98,
      characterStyle: "heavy-crosshatch-berserk",
      environmentStyle: "gothic-castle-ruins",
      lineArtStrength: 96,
      shadingStrength: 95,
      colorLevel: 0,
      realismLevel: 68,
      textureLevel: 92,
      detailLevel: 98,
    },
    promptKeywords: [
      "Kentaro Miura Berserk inspired dark fantasy manga",
      "hyper-detailed ink crosshatching",
      "grim medieval gothic atmosphere",
      "weathered forged steel textures",
      "dramatic stark ink pooling and cast shadows",
      "monochrome ink masterpiece",
    ],
    negativeKeywords: ["color", "rainbow", "chibi", "cute cartoon", "smooth 3d plastic"],
  },
];

export const DEFAULT_NEGATIVE_CONSTRAINTS = [
  "extra limbs",
  "missing fingers",
  "deformed hands",
  "distorted facial features",
  "inconsistent character attire",
  "random gibberish text in drawing",
  "blurry background",
  "watermarks or signatures",
  "oversaturated neon flares",
  "plastic 3d render look",
  "poor anatomy",
  "cut off heads",
];

export const DEFAULT_MODELS: ModelProviderConfig[] = [
  {
    id: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash (Multimodal & Reasoning)",
    provider: "google-gemini",
    modelName: "gemini-3.8-flash",
    modality: "multimodal",
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    supportsImageInput: true,
    supportsImageOutput: false,
    supportsStreaming: true,
    enabled: true,
    costPer1kTokens: 0.00015,
  },
  {
    id: "gemini-3.5-flash-lite",
    name: "Gemini 3.5 Flash-Lite (High Speed)",
    provider: "google-gemini",
    modelName: "gemini-3.5-flash-lite",
    modality: "text",
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    supportsImageInput: true,
    supportsImageOutput: false,
    supportsStreaming: true,
    enabled: true,
    costPer1kTokens: 0.000075,
  },
  {
    id: "gemini-3-pro-image",
    name: "Gemini 3 Pro Image (Studio Quality)",
    provider: "google-gemini",
    modelName: "gemini-3-pro-image",
    modality: "image",
    contextWindow: 65536,
    maxOutputTokens: 4096,
    supportsImageInput: true,
    supportsImageOutput: true,
    supportsStreaming: false,
    enabled: true,
    imageDimensions: { width: 1024, height: 1024 },
  },
  {
    id: "gemini-3.1-flash-image",
    name: "Gemini 3.1 Flash Image (Ultra-Fast)",
    provider: "google-gemini",
    modelName: "gemini-3.1-flash-image",
    modality: "image",
    contextWindow: 65536,
    maxOutputTokens: 4096,
    supportsImageInput: true,
    supportsImageOutput: true,
    supportsStreaming: false,
    enabled: true,
    imageDimensions: { width: 1024, height: 1024 },
  },
  {
    id: "custom-endpoint-model",
    name: "Custom Model (Self-Hosted / Enterprise)",
    provider: "custom-endpoint",
    modelName: "custom-v1",
    modality: "multimodal",
    contextWindow: 32768,
    maxOutputTokens: 4096,
    supportsImageInput: true,
    supportsImageOutput: true,
    supportsStreaming: false,
    enabled: false,
    isCustom: true,
    customEndpoint: "https://api.your-model-gateway.internal/v1",
    apiKeyConfigured: false,
  },
];

export const TEMPLATE_LAYOUTS: {
  id: PageLayoutTemplate;
  name: string;
  description: string;
  defaultPanelCount: number;
}[] = [
  {
    id: "single",
    name: "Full Page Splash",
    description: "One epic full-bleed panel for dramatic moments, covers, or climax scenes.",
    defaultPanelCount: 1,
  },
  {
    id: "grid-4",
    name: "Classic 4-Panel (Yonkoma / Grid)",
    description: "Balanced 2x2 grid ideal for pacing, comedy, and steady storytelling.",
    defaultPanelCount: 4,
  },
  {
    id: "manga-dynamic",
    name: "Dynamic Manga Action (5 Panels)",
    description: "Asymmetrical diagonal cut panels for intense battles, reveals, and motion.",
    defaultPanelCount: 5,
  },
  {
    id: "classic-6",
    name: "Graphic Novel 6-Panel",
    description: "Standard American/European comic rhythm with 3 tiers of 2 panels.",
    defaultPanelCount: 6,
  },
  {
    id: "cinematic-wide",
    name: "Cinematic Widescreen (3 Panels)",
    description: "Three widescreen 16:9 panels focusing on environment, dialogue, and reaction.",
    defaultPanelCount: 3,
  },
  {
    id: "webtoon-strip",
    name: "Webtoon Vertical Strip",
    description: "Mobile-first seamless vertical flow with spacious panel gutter pacing.",
    defaultPanelCount: 4,
  },
];
