import { ModelAnimationPreset } from "@/types/animation";

export const MODEL_ANIMATION_PRESETS: ModelAnimationPreset[] = [
  {
    id: "anim_sakuga_2d",
    name: "Sakuga 2D Action",
    category: "2d-sakuga",
    tagline: "High-Octane Japanese Anime Keyframe Masterclass",
    badge: "⚡ Sakuga 2D",
    icon: "Zap",
    description: "Dynamic perspective foreshortening, kinetic impact frames, crackling elemental auras, and fluid keyframe smears in Ufotable/MAPPA style.",
    frameRate: "Variable 24-60 FPS Impact Timing",
    cameraMovement: "Rapid Dutch-angle tracking dive with speed blur",
    lightingPacing: "High-contrast rim glow with chromatic flare bursts",
    motionKeywords: [
      "high-octane sakuga anime keyframe",
      "dynamic action foreshortening",
      "kinetic motion blur streaks",
      "electric energy sparks",
      "impact frame smear line",
      "dramatic camera plunge perspective",
    ],
    autoPromptTemplate:
      "High-octane sakuga anime key visual, explosive foreshortened action posture, crackling kinetic energy sparks, high-speed motion blur lines, sharp cel shading with radiant rim lighting, ufotable anime production masterpiece.",
    suggestedActionPrompts: [
      {
        title: "Explosive Combat Clash",
        description: "Two fighters colliding with shockwave distortion",
        prompt: "Explosive anime sakuga combat clash, two fighters colliding in mid-air, concentric shockwave air ripples, blinding kinetic spark discharge, extreme wide-angle dynamic perspective.",
      },
      {
        title: "High-Speed Rooftop Chase",
        description: "Agile sprint across midnight skyscrapers",
        prompt: "High-speed anime rooftop sprint, character leaping across neon skyscraper chasms, wind-whipped cape and hair, glowing cityscape below, dynamic low-angle tracking shot.",
      },
      {
        title: "Energy Awakening Surge",
        description: "Hero powering up with intense atmospheric aura",
        prompt: "Anime power awakening, crackling ethereal aura swirling around hero, ground shattering into floating debris, intense glowing irises, dramatic upward camera tilt with lens flare.",
      },
    ],
    accentColor: "#00E5FF",
    previewGradient: "from-cyan-500/20 to-blue-600/30",
  },
  {
    id: "anim_3d_cinematic",
    name: "3D Feature Cinematic",
    category: "3d-cinematic",
    tagline: "Theatrical Feature-Film CGI & Volumetric Octane Render",
    badge: "🎬 3D Cinematic",
    icon: "Film",
    description: "Raytraced reflections, subsurface skin scattering, atmospheric volumetric smoke, depth-of-field bokeh, and hyper-detailed 3D cinematic polish.",
    frameRate: "Theatrical 24 FPS with Panavision motion blur",
    cameraMovement: "Smooth dolly-in with anamorphic shallow focus",
    lightingPacing: "Three-point Hollywood cinema key & warm bounce fills",
    motionKeywords: [
      "theatrical 3d animated movie frame",
      "volumetric smoke shafts",
      "subsurface scattering",
      "anamorphic lens flare",
      "octane render realism",
      "cinematic depth of field bokeh",
    ],
    autoPromptTemplate:
      "Cinematic 3D animated feature film still, raytraced atmospheric volumetric lighting, rich textural subsurface scattering, cinematic shallow depth of field, anamorphic bokeh, Pixar and Unreal Engine 5 production caliber.",
    suggestedActionPrompts: [
      {
        title: "Dramatic Monologue Stare",
        description: "Emotional close-up with soft cinematic bokeh",
        prompt: "Cinematic 3D close-up portrait, intense emotional gaze, delicate tears catching warm rim lighting, soft creamy background bokeh, ultra-detailed skin and hair texture.",
      },
      {
        title: "Atmospheric Ancient Vault",
        description: "Hero exploring grand mysterious ruins",
        prompt: "Cinematic wide-shot 3D interior, lone explorer standing before colossal ancient monolith, volumetric golden dust motes piercing vaulted ceiling, majestic scale and shadows.",
      },
      {
        title: "Heavy Weather Battle",
        description: "Rain-lashed cinematic duel with puddles and mist",
        prompt: "Cinematic 3D rainy duel, rain splashing off metallic armor, glistening wet pavement reflections, volumetric steam rising from asphalt, cinematic widescreen 2.39:1 framing.",
      },
    ],
    accentColor: "#F59E0B",
    previewGradient: "from-amber-500/20 to-orange-600/30",
  },
  {
    id: "anim_spider_halftone",
    name: "Spider-Verse Halftone",
    category: "spider-verse",
    tagline: "Stepped 12FPS Comic Multiverse Print Animation",
    badge: "🕷️ Spider-Verse",
    icon: "Layers",
    description: "Animated on 2s (12fps snappy timing), CMYK print misregistration, chromatic aberration fringing, Ben-Day halftone dot textures, and bold graffiti ink lines.",
    frameRate: "Stepped 12 FPS (On Twos) with stylized smears",
    cameraMovement: "Extreme rotational whip-pan with chromatic split",
    lightingPacing: "Graphic neon rim lights with halftone screen gradients",
    motionKeywords: [
      "Spider-Verse inspired animated comic frame",
      "visible CMYK halftone dot screen",
      "chromatic aberration color separation",
      "stepped 12fps dynamic animation pose",
      "bold comic ink hatch contours",
      "graffiti aesthetic motion lines",
    ],
    autoPromptTemplate:
      "Spider-Verse animated comic still, stylized stepped 12fps silhouette pose, CMYK color offset misregistration, visible Ben-Day halftone dots, bold expressive brush contour, dynamic graffiti comic burst.",
    suggestedActionPrompts: [
      {
        title: "Gravity-Defying Leap",
        description: "Dynamic swing through neon city chasms",
        prompt: "Spider-Verse style aerial dive, hero descending upside down through neon billboards, comic speed lines, halftone dot gradient shading, chromatic color split edges.",
      },
      {
        title: "Sound Effect Impact",
        description: "Punch landing with graphic comic SFX blast",
        prompt: "Kinetic comic punch impact, stylized 'THWIP-KRAK!' onomatopoeia letters rendered in 3D graffiti, distortion waves radiating outward, comic print dot texture.",
      },
    ],
    accentColor: "#FF2A8D",
    previewGradient: "from-pink-500/20 to-rose-600/30",
  },
  {
    id: "anim_ghibli_watercolor",
    name: "Ghibli Hand-Drawn 2D",
    category: "ghibli-watercolor",
    tagline: "Heartwarming Hand-Painted Anime with Gouache Scenery",
    badge: "🍃 Ghibli 2D",
    icon: "Feather",
    description: "Delicate gouache backgrounds, billowing cumulonimbus clouds, wind-swept garments, gentle watercolor blooms, and nostalgic storybook emotional pacing.",
    frameRate: "Traditional 18-24 FPS organic hand-drawn pacing",
    cameraMovement: "Gentle panoramic pan revealing lush pastoral vista",
    lightingPacing: "Dappled golden-hour sunlight filtered through leaves",
    motionKeywords: [
      "Studio Ghibli hand-drawn anime aesthetic",
      "lush painted gouache meadow background",
      "billowing summer cumulus clouds",
      "wind-swept hair and garments",
      "warm dappled sunlight diffusion",
      "whimsical storybook nostalgia",
    ],
    autoPromptTemplate:
      "Hayao Miyazaki inspired 2D hand-painted animation still, lush verdant hillside dotted with wildflowers, towering white clouds in azure sky, gentle breeze swaying clothing, soft nostalgic watercolor warmth.",
    suggestedActionPrompts: [
      {
        title: "Peaceful Meadow Discovery",
        description: "Serene moment of discovery in magical nature",
        prompt: "Ghibli aesthetic scenic still, character resting under a colossal ancient weeping willow, golden sunbeams piercing emerald canopy, whimsical glowing forest spirits.",
      },
      {
        title: "Whimsical Flight Sequence",
        description: "Gliding through clouds over seaside village",
        prompt: "Ghibli style flight sequence, character soaring on wooden glider above red-roofed coastal village, sparkling turquoise ocean below, soft watercolor cloud edges.",
      },
    ],
    accentColor: "#10B981",
    previewGradient: "from-emerald-500/20 to-teal-600/30",
  },
  {
    id: "anim_cyberpunk_cel",
    name: "Cyberpunk Cel Glitch",
    category: "cyberpunk-cel",
    tagline: "Futuristic Neo-Tokyo Animation with Hologram Glitches",
    badge: "🌆 Cyberpunk Cel",
    icon: "Cpu",
    description: "Heavy black ink contours, neon cyan/magenta rim glows, rainy asphalt reflections, holographic artifact scanlines, and high-frequency motion trails.",
    frameRate: "Fluid 30-60 FPS with digital glitch keyframes",
    cameraMovement: "Low-angle tilted Dutch-camera tracking neon street",
    lightingPacing: "Strobe neon reflections and volumetric laser beams",
    motionKeywords: [
      "cyberpunk neo-tokyo cel animation",
      "holographic glitch scanlines",
      "electric cyan and magenta rim light",
      "rain-soaked asphalt reflections",
      "futuristic cybernetic visor interface",
      "speed trail light streaks",
    ],
    autoPromptTemplate:
      "High-contrast cyberpunk cel anime keyframe, rain-drenched dark alleys reflecting neon billboards, holographic HUD glitch artifacts, glowing fiber-optic cybernetics, Akira and Cyberpunk Edgerunners style.",
    suggestedActionPrompts: [
      {
        title: "Neon Alley Standoff",
        description: "Cybernetic operative readying plasma blades",
        prompt: "Cyberpunk alleyway duel, operative unsheathing glowing plasma katana, rain droplets sizzling on blade, neon signs reflecting in wet pavement, holographic error code overlay.",
      },
      {
        title: "Data Stream Cyber-Dive",
        description: "Character jacked into virtual network construct",
        prompt: "Cyberpunk virtual reality dive, character suspended in zero-g surrounded by cascading green data streams, geometric wireframe grid, glowing optic implants.",
      },
    ],
    accentColor: "#8B5CF6",
    previewGradient: "from-purple-500/20 to-indigo-600/30",
  },
  {
    id: "anim_dark_gothic",
    name: "Gothic Dark Fantasy",
    category: "dark-gothic",
    tagline: "Grim Medieval Ink & Ethereal Ember Particles",
    badge: "⚔️ Gothic Dark",
    icon: "Shield",
    description: "Heavy ink chiaroscuro cross-hatching, ominous castle silhouettes, floating glowing embers, weathered steel plate armor, and Elden Ring/Berserk atmosphere.",
    frameRate: "Weighty 24 FPS with deliberate heavy weapon inertia",
    cameraMovement: "Low-angle menacing gaze looking up at colossal boss",
    lightingPacing: "Smoldering campfire amber cutting through pitch gloom",
    motionKeywords: [
      "Kentaro Miura Berserk dark fantasy manga aesthetic",
      "hyper-detailed ink crosshatching",
      "floating cinder embers",
      "weathered battle-worn iron armor",
      "dramatic grim chiaroscuro shadows",
      "ominous gothic castle ruins",
    ],
    autoPromptTemplate:
      "Dark medieval fantasy animation still, battered knight gripping greatsword amidst crumbling gothic cathedral ruins, glowing floating embers in mist, intense high-contrast crosshatch inking, FromSoftware and Berserk grandeur.",
    suggestedActionPrompts: [
      {
        title: "Colossal Demon Encounter",
        description: "Lone knight facing towering shadowy leviathan",
        prompt: "Dark fantasy confrontation, lone warrior looking up at towering horned shadow monstrosity with burning red eyes, ruined gothic archway, blood moon in sky.",
      },
      {
        title: "Emberlit Campfire Rest",
        description: "Brooding knight resting beside a dying flame",
        prompt: "Atmospheric dark fantasy campfire, wounded warrior in dented iron armor tending solitary campfire, dancing golden embers, deep pitch shadows in surrounding forest.",
      },
    ],
    accentColor: "#EF4444",
    previewGradient: "from-red-600/20 to-zinc-800/40",
  },
  {
    id: "anim_retro_cartoon",
    name: "90s Saturday Cartoon",
    category: "retro-cartoon",
    tagline: "Bold Outlines, Squash & Stretch, Saturated Energy",
    badge: "💥 90s Cartoon",
    icon: "Sparkles",
    description: "Thick ink brush outlines, classic squash-and-stretch animation physics, bold primary palettes, dynamic action speed lines, and comic exclamation bursts.",
    frameRate: "Energetic 12-24 FPS with exaggerated holds",
    cameraMovement: "Direct head-on action burst with comedic pop-in",
    lightingPacing: "Bright flat theatrical key with minimal shadow",
    motionKeywords: [
      "classic 1990s animated television cartoon",
      "bold black ink stroke contours",
      "exaggerated squash and stretch silhouette",
      "vibrant saturated primary colors",
      "dynamic action burst particles",
      "nostalgic Saturday morning comic aesthetic",
    ],
    autoPromptTemplate:
      "Vintage 90s Saturday morning cartoon still, bold animated lines, punchy saturated colors, dynamic heroic action pose with comic impact stars, retro animation cel warmth.",
    suggestedActionPrompts: [
      {
        title: "Heroic Double Take",
        description: "Exaggerated comedic reaction or surprise",
        prompt: "90s cartoon comedic surprise, character jumping in air with exaggerated shocked expression, lightning bolt exclamation mark above head, bold ink outline.",
      },
      {
        title: "Dynamic Team Lineup",
        description: "Squad posing heroically before city skyline",
        prompt: "90s cartoon squad hero lineup, three diverse characters in bold superhero costumes striking confident power poses on skyscraper rooftop, bright blue sky.",
      },
    ],
    accentColor: "#F43F5E",
    previewGradient: "from-rose-500/20 to-orange-500/30",
  },
  {
    id: "anim_kawaii_chibi",
    name: "Kawaii Chibi Emote",
    category: "kawaii-chibi",
    tagline: "Super-Deformed Adorable Animated Expressions",
    badge: "🌸 Kawaii Chibi",
    icon: "Heart",
    description: "2-head-tall proportions, sparkling star eyes, bouncy sweat-drop emotes, soft pastel gradient hues, and heartwarming manga slice-of-life humor.",
    frameRate: "Cute 12 FPS bounce cycle with emoticon bursts",
    cameraMovement: "Frontal cute portrait with sparkling background",
    lightingPacing: "Soft pastel dream glow with sparkling star aura",
    motionKeywords: [
      "adorable chibi anime character",
      "sparkling celestial star eyes",
      "cute animated sweat-drop emote",
      "pastel pastel gradient lighting",
      "soft rounded contours",
      "manga slice-of-life humor",
    ],
    autoPromptTemplate:
      "Chibi anime character illustration, super-deformed cute proportions, sparkling star-filled eyes, adorable blushing cheeks, floating pastel stars and hearts, heartwarming webtoon comic panel.",
    suggestedActionPrompts: [
      {
        title: "Sparkling Excitement",
        description: "Chibi character overjoyed with stars in eyes",
        prompt: "Chibi character celebrating with hands clasped together, oversized sparkling eyes with gold stars, pink cheek blush, floating musical notes and sparkles.",
      },
      {
        title: "Comedic Panic",
        description: "Chibi flailing with giant sweat drop",
        prompt: "Chibi character in hilarious panic, waving arms wildly like a windmill, giant translucent sweat drop on temple, wavy comedic mouth, cartoon speed dust at feet.",
      },
    ],
    accentColor: "#EC4899",
    previewGradient: "from-pink-400/20 to-purple-400/30",
  },
];
